### ISSUE TITLE
Conversion between .uisnapshot and offline file (.json) format

### ISSUE THREAD

**Issue by TAICHEEZ** [dmotte/ui24rsc#1]
# I want a converter between literally snapshot (.uisnapshot) file and offline file (.json) and (.yml) .

**Comment by dmotte** [comment]
Hey there! Thanks for opening this issue 🙂 

Unfortunately this project is specific to JSON Soundcraft format. By the way, feel free to extend it or take inspiration. If you end up implementing this feature yourself let me know 😉

**Comment by TAICHEEZ** [comment]
Thanks for replying. 
Definitely, I only mentioned about soundcraft ui24r. 

Probably, you are describing the offline file as snapshots, I think.
That's a bit confusing matter for users of the ui24r.
Because ui24r's snapshot has "xxxxxxx.uisnapshot" extension literally. 

We can export snapshots to the USB drive inserted on the device of ui24r by clicking "Export Show". This is the snapshot. 

And soundcraft is naming the file which has the  "xxxxxxxx.json" extension as the "offline file".

Actually the "xxxxxxxx.uisnapshot" is also a readable text list.

Unfortunately I don' have a skill for programming.
If you'll got a interest, I can be happy, Thanks.

**Comment by dmotte** [comment]
Hi @TAICHEEZ, yes in fact I am referring to "Offline Files" as "snapshots". You are right, this is a bit confusing. I will now make the documentation more clear. Thanks for pointing it out :)

BTW, offline files are also readable text. In fact, the two formats are very similar. For example, you can use any online JSON formatter (e.g. https://jsoneditoronline.org/) to make an offline file content more tidy and readable.

That said, this project is specific to "offline files". Your request is about converting between _uisnapshot_ and _offline files_, which of course would be a very interesting feature, but it's another task which deserves its separate tool. Maybe I will think about it in the future if I have some time :)

**Comment by dmotte** [comment]
JFYI @TAICHEEZ there is now a fork of this project, made by @HighTechHarmony, which I guess provides the functionality you were asking for:

https://github.com/HighTechHarmony/SoundcraftUiSC

I know almost 4 years have passed, but now we have it, so it's worth mentioning here :)
