### ISSUE TITLE
Need a better understanding of the categories in the Json files.

### ISSUE THREAD

**Issue by patrick-keogh** [dmotte/ui24rsc#3]
I have built a much less ambitious pretty printer for the Uixx Json files.
Most of the key names are pretty obvious, but some elude me.

As a translation dictionary I have:
{"i":"Input ", "a":"Aux ", "f":"FX ", "s":"Subgroup ", "l":"L", "m":"Master", "p":"P"}

So what do "l" and "p" stand for? Happy if you can offer any advice (and prepared for a "DOH" moment.

**Comment by dmotte** [comment]
Hey @patrick-keogh! Great that you're working on a pretty-printer for this :) and thanks for sharing your translation dictionary with us.

About the L and P letters, I think that they stand for **Line** (the RCA connectors input) and **Player** (the built-in music player), but I'm not 100% sure of course. These just make sense in my mind :wink:

Good luck with your pretty-printer and happy coding!

**Comment by patrick-keogh** [comment]
Thanks, as I expected it was "obvious".

Here is the basics of the pretty printer, feel free to use as CC.

Patrick

**Comment by patrick-keogh** [comment]
Final version. It now prompts for which category you want to see and does
some minimum formatting.

**Comment by dmotte** [comment]
Hey Patrick, sorry but I can't see it. Are you trying to send it via e-mail attachment? I'm afraid it doesn't work in GitHub. I guess you'll have to create a public repo or gist to share your code

**Comment by patrick-keogh** [comment]
OK, it is at
https://gist.github.com/patrick-keogh/62d3f5200aa975dbe1604a58fb0c7c9a
